### ISSUE TITLE
Vendor Site: Add social media to home page

### ISSUE THREAD

**Issue by thomas-thackery** [woodwarddesign/GWG-Clothing#11]

**Comment by thomas-thackery** [comment]
1. Twitter
2. Instagram
3. Facebook
4. Pintrest
5. You Tube

**Comment by thomas-thackery** [comment]
@gwgjan Can you get Mike the credentials (privately) for these social media accounts?

**Comment by gwgjan** [comment]
@kveldalf I can make Mike an admin on our FB account. I will have Callie connect with him for the rest of the information. Is this something he needs temporarily to set up everything or ongoing?

**Comment by gwgjan** [comment]
I see I have already made Mike an admin for FB. @mlwoodward if you are not able to access it, please let me know. Thanks
